openapi: 3.0.1
info:
  title: Notes API
  description: API documentation for Notes and User Authentication
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local development server !
paths:
  /register:
    post:
      summary: Register a new user for
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                phone_number:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '422':
          description: Validation errors

  /login:
    post:
      summary: User login
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized

  /profile:
    get:
      summary: Get user profile
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile fetched successfully
        '401':
          description: Unauthorized

  /forgetpassword:
    post:
      summary: Request password reset
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password reset request sent
        '404':
          description: User not found

  /resetpassword/{id}:
    post:
      summary: Reset password using OTP
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                new_password:
                  type: string
      responses:
        '200':
          description: Password updated successfully
        '422':
          description: Invalid OTP or error

  /notes/create:
    post:
      summary: Create a new note
      tags:
        - Notes
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                color:
                  type: string
      responses:
        '201':
          description: Note created successfully
        '422':
          description: Validation errors

  /notes/getnote:
    get:
      summary: Get all notes
      tags:
        - Notes
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of notes
        '401':
          description: Unauthorized

  /notes/getnotebyid/{id}:
    get:
      summary: Get a specific note by ID
      tags:
        - Notes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Note fetched successfully
        '404':
          description: Note not found
        '401':
          description: Unauthorized

  /notes/archive/{id}:
    put:
      summary: Archive/unarchive a note
      tags:
        - Notes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Note archived/unarchived successfully
        '422':
          description: Error in toggling archive

  /notes/trash/{id}:
    put:
      summary: Move note to trash
      tags:
        - Notes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Note moved to trash successfully
        '422':
          description: Error in trash operation

  /notes/update_color/{id}/{color}:
    put:
      summary: Update note color
      tags:
        - Notes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: color
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Note color updated successfully
        '422':
          description: Error updating color

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
